-- MySQL Script generated by MySQL Workbench
-- Mon Oct  8 14:57:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema legoDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema legoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `legoDB` DEFAULT CHARACTER SET utf8 ;
USE `legoDB` ;

-- -----------------------------------------------------
-- Table `legoDB`.`UserTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legoDB`.`UserTable` ;

CREATE TABLE IF NOT EXISTS `legoDB`.`UserTable` (
  `email` VARCHAR(256) NOT NULL,
  `username` VARCHAR(256) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `rolegroup` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `legoDB`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legoDB`.`Orders` ;

CREATE TABLE IF NOT EXISTS `legoDB`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `length` BIGINT(8) NOT NULL,
  `width` BIGINT(8) NOT NULL,
  `quantityheigth` BIGINT(8) NOT NULL,
  `orderdater` datetime NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `legoDB`.`OrderDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `legoDB`.`OrderDetails` ;

CREATE TABLE IF NOT EXISTS `legoDB`.`OrderDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `email`),
  INDEX `fk_usertable_email_idx` (`email` ASC),
  CONSTRAINT `fk_order_id`
    FOREIGN KEY (`id`)
    REFERENCES `legoDB`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usertable_email`
    FOREIGN KEY (`email`)
    REFERENCES `legoDB`.`UserTable` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
